### ISSUE TITLE
Error using reverse proxy

### ISSUE THREAD

**Issue by AlejandroMoraG** [bludit/docker#10]
Hello,

First of all, thank you for the great work.  I am having trouble loading bludit content through a reverse proxy:
![image](https://user-images.githubusercontent.com/43340016/85773971-50bdc900-b716-11ea-9d7a-bdf311d40162.png)

My configuration for docker-compose is as follows:
`version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: bludit/docker
    restart: always
    expose:
      - "80"
    volumes:
      - /home/webadmin/blog/bludit:/usr/share/nginx/html/bl-content
    environment:
      - VIRTUAL_HOST=example.com
      - LETSENCRYPT_HOST=example.com
      - LETSENCRYPT_EMAIL=admin@example.com
volumes:
  certs:
  html:
  vhostd:`

I have tried removing the volume config for bludit, but still showing the same problem.  I have also tried to include the following in the jwilder/nginx-proxy configuration:
`proxy_pass_request_headers on;`

But I also cannot load the web correctly. Thanks for your help.

**Comment by dignajar** [comment]
can you open the `Inspect` from the browser and check the errors? looks like the base URL is wrong in the settings.

**Comment by AlejandroMoraG** [comment]
Hi,
Yes, the problem was the base URL in the site configuration. After run the contaner, I was enter to de admin site and change the option, to allow HTTPS traffic:
![image](https://user-images.githubusercontent.com/43340016/86055067-28560780-ba53-11ea-982f-bc8753e5ae0b.png)
Then, all website loaded correctly. Can be good add any enviroment var to active https in the moment to create the docker container. Thanks for your time and sorry for bothering you.
