### ISSUE TITLE
Image with latest-tag not available from Docker Hub

### ISSUE THREAD

**Issue by bobcanthelpyou** [bludit/docker#2]
When running `docker pull bludit/docker` the pull doesn't work.

```
:~# docker pull bludit/docker
Using default tag: latest
Error response from daemon: manifest for bludit/docker:latest not found
```

Why is the latest tag missing?

Using `docker pull bludit/docker:3.4.0` works. But documentation on Github and Docker Hub state the latest tag, only.

Is it a Docker Hub issue? https://hub.docker.com/r/bludit/docker/builds/

**Comment by dignajar** [comment]
Hi,
by mistake I deleted the tag `latest`, I recrete it.
Thank for report it.

**Comment by bobcanthelpyou** [comment]
Thanks the tag is available again =)
